---
title: "aguasan-pitch-slides-openwashdata-lschoebitz"
format: html
---

#

We analysed X number of WASH research articles across X number of journals for their data availability statements.

A quiz:

## Q: Number (%) of papers stating "available in paper":

- A
- B
- C

## Q: Number (%) of papers stating "available on request":


- A
- B
- C

## Q: Number (%) of papers stating "available in an online repository":


- A
- B
- C

# 

With some many papers stating "available in paper", we looked at the supplementary files

## Q: Number (%) of papers with data in "machine-readable, non-proprietary file type format"

CSV (words and commas)!

## Point

That's what we need to change as researchers and after three years of research funding, teaching live online classes, and investing into workflows, we are ready to change the practice the entire sector.

#

## Q: Since 2015, the SGDs for sanitation 6.2.1 include data along the sanitation service chain. Toilets aside, how many countries have at least one data point for variables on emptying, transport and treatment of faecal sludge?

- A
- B
- C

## Q: How many of those countries are categorised as low- and middle-income countries?

- A
- B
- C




Out of 10'000 WASH research articles, how many have shared their data alongside the research article?

- A:
- B: 
- C:



